# Generated by Django 4.2.27 on 2026-02-09 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series_order', models.PositiveIntegerField(help_text='Position in the series (1-20 for your 20-book series)')),
                ('description', models.TextField(blank=True)),
                ('word_count_target', models.PositiveIntegerField(default=160000, help_text='Target word count for this book')),
                ('current_word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('drafting', 'Drafting'), ('editing', 'Editing'), ('complete', 'Complete'), ('published', 'Published')], default='planning', max_length=20)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['series_order'],
                'unique_together': {('user', 'series_order')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='timeline.book')),
            ],
            options={
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('supporting', 'Supporting'), ('minor', 'Minor')], default='supporting', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Physical description, personality, background')),
                ('motivation', models.TextField(blank=True, help_text='What drives this character?')),
                ('color_code', models.CharField(default='#3498db', help_text='Hex color code for timeline visualization (e.g., #3498db)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Is this character still active in the current narrative?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduction_book', models.ForeignKey(blank=True, help_text='Which book does this character first appear in?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_characters', to='timeline.book')),
                ('introduction_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_characters', to='timeline.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('theme', 'Theme'), ('location', 'Location'), ('subplot', 'Subplot'), ('motif', 'Motif'), ('tone', 'Tone'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(default='#95a5a6', help_text='Hex color code for visual identification', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what happens in this event/scene')),
                ('sequence_order', models.PositiveIntegerField(default=0, help_text='Order of this event in the narrative sequence')),
                ('chronological_order', models.PositiveIntegerField(default=0, help_text='Order of this event in actual story chronology (for flashbacks/non-linear narratives)')),
                ('story_date', models.CharField(blank=True, help_text="Date/time within your story world (e.g., 'June 2024' or 'Day 3')", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Where does this event take place?', max_length=200)),
                ('emotional_tone', models.CharField(choices=[('tension', 'High Tension'), ('action', 'Action'), ('emotional', 'Emotional'), ('reflective', 'Reflective'), ('humorous', 'Humorous'), ('dark', 'Dark'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('story_beat', models.CharField(blank=True, choices=[('exposition', 'Exposition'), ('inciting', 'Inciting Incident'), ('rising', 'Rising Action'), ('climax', 'Climax'), ('falling', 'Falling Action'), ('resolution', 'Resolution'), ('setup', 'Setup/Plant'), ('payoff', 'Payoff')], max_length=20)),
                ('tension_level', models.PositiveIntegerField(default=5, help_text='Tension/intensity level (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Private notes, reminders, or research notes for this event')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Approximate word count for this scene')),
                ('is_written', models.BooleanField(default=False, help_text='Have you actually written this scene yet?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.chapter')),
                ('characters', models.ManyToManyField(blank=True, help_text='All characters involved in this event', related_name='events', to='timeline.character')),
                ('pov_character', models.ForeignKey(blank=True, help_text="Which character's POV is this scene from?", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pov_events', to='timeline.character')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='timeline.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('ally', 'Ally/Friend'), ('enemy', 'Enemy/Rival'), ('romantic', 'Romantic'), ('family', 'Family'), ('mentor', 'Mentor/Student'), ('business', 'Business/Professional'), ('neutral', 'Neutral/Acquaintance')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Describe the nature of this relationship')),
                ('strength', models.PositiveIntegerField(default=5, help_text='Strength/intensity of relationship (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='timeline.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='timeline.character')),
                ('starts_at_event', models.ForeignKey(blank=True, help_text='When does this relationship begin or become significant?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_starting', to='timeline.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('character_a', 'character_b')},
            },
        ),
    ]
