# Generated by Django 6.0.2 on 2026-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this book.', null=True, upload_to='book_covers/'),
        ),
    ]
