# Generated by Django 4.2.27 on 2026-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_html',
            field=models.TextField(blank=True, help_text='Rich text content in HTML format', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Rich text content in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Brief summary of the scene (optional)'),
        ),
    ]
