# Generated by Django 4.2.27 on 2026-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_event_content_html_event_content_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_id',
            field=models.CharField(blank=True, help_text='ID of the selected cartoon avatar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a custom profile picture', null=True, upload_to='character_profiles/'),
        ),
    ]
