# Generated by Django 4.2.27 on 2026-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_character_avatar_id_character_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_file',
            field=models.FileField(blank=True, help_text='Upload your chapter manuscript (.docx or .txt) to automatically calculate word count.', null=True, upload_to='chapters/'),
        ),
    ]
