# Generated by Django 4.2.27 on 2026-02-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_chapter_chapter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, help_text='Paste your chapter content here.'),
        ),
    ]
