# Generated by Django 4.2.27 on 2026-02-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_aifocustask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifocustask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
