# Generated by Django 4.2.27 on 2026-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='goals',
            field=models.TextField(blank=True, help_text='Long-term and short-term objectives'),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True, help_text='Key personality traits and quirks'),
        ),
    ]
