# Generated by Django 4.2.27 on 2026-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_writingdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('drafting', 'Drafting'), ('editing', 'Editing'), ('complete', 'Complete'), ('published', 'Published')], default='planning', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('supporting', 'Supporting'), ('minor', 'Minor')], default='supporting', max_length=100),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('ally', 'Ally/Friend'), ('enemy', 'Enemy/Rival'), ('romantic', 'Romantic'), ('family', 'Family'), ('mentor', 'Mentor/Student'), ('business', 'Business/Professional'), ('neutral', 'Neutral/Acquaintance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='emotional_tone',
            field=models.CharField(choices=[('tension', 'High Tension'), ('action', 'Action'), ('emotional', 'Emotional'), ('reflective', 'Reflective'), ('humorous', 'Humorous'), ('dark', 'Dark'), ('neutral', 'Neutral')], default='neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='story_beat',
            field=models.CharField(blank=True, choices=[('exposition', 'Exposition'), ('inciting', 'Inciting Incident'), ('rising', 'Rising Action'), ('climax', 'Climax'), ('falling', 'Falling Action'), ('resolution', 'Resolution'), ('setup', 'Setup/Plant'), ('payoff', 'Payoff')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('theme', 'Theme'), ('location', 'Location'), ('subplot', 'Subplot'), ('motif', 'Motif'), ('tone', 'Tone'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.DeleteModel(
            name='WritingDeadline',
        ),
    ]
