# Generated by Django 4.2.27 on 2026-02-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_alter_book_status_alter_character_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('importing', 'Import in Progress'), ('planning', 'Planning'), ('drafting', 'Drafting'), ('editing', 'Editing'), ('complete', 'Complete'), ('published', 'Published')], default='planning', max_length=100),
        ),
    ]
