# Generated by Django 4.2.27 on 2026-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='import_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='import_status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
