# Generated by Django 4.2.27 on 2026-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_book_import_progress_book_import_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_import_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
