# Generated by Django 4.2.27 on 2026-02-11 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0015_book_last_import_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('location', 'Location'), ('lore', 'Lore'), ('faction', 'Faction'), ('rule', 'Rule/Magic System'), ('item', 'Item/Artifact'), ('culture', 'Culture/Society'), ('creature', 'Creature/Species'), ('other', 'Other')], default='location', max_length=20)),
                ('content', models.TextField(help_text='Detailed description of this world element.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='world_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_entries', to='timeline.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'World Entries',
                'ordering': ['category', 'title'],
            },
        ),
    ]
