# Generated by Django 4.2.27 on 2026-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0016_worldentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='aliases',
            field=models.CharField(blank=True, help_text="Comma-separated alternate names (e.g. 'Mum, Mrs. Smith, Sarah')", max_length=500),
        ),
    ]
