# Generated by Django 4.2.27 on 2026-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0017_character_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='deep_dive_notes',
            field=models.TextField(blank=True, help_text='Last generated AI deep dive for this character', null=True),
        ),
    ]
