# Generated by Django 4.2.27 on 2026-02-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_character_deep_dive_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_type',
            field=models.CharField(choices=[('exact', 'Exact Date'), ('fuzzy', 'Fuzzy/Uncertain'), ('ongoing', 'Ongoing/Event Span'), ('relative', 'Relative Date'), ('none', 'No Date Yet')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='earliest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevent accidental automatic rescheduling'),
        ),
        migrations.AddField(
            model_name='event',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='narrative_order',
            field=models.PositiveIntegerField(blank=True, help_text='Explicit order for narrative view (reading order)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='relative_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='relative_description',
            field=models.CharField(blank=True, help_text="e.g., 'Three days later', 'One week after'", max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='relative_to_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_events', to='timeline.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='scene_type',
            field=models.CharField(choices=[('scene', 'Scene'), ('exposition', 'Exposition/Infodump'), ('flashback', 'Flashback'), ('flashforward', 'Flashforward'), ('interlude', 'Interlude'), ('teaser', 'Cold Open/Teaser')], default='scene', max_length=15),
        ),
    ]
