# Generated by Django 4.2.27 on 2026-02-12 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0019_event_date_event_date_type_event_earliest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrelationship',
            name='evolution',
            field=models.TextField(blank=True, help_text='Notes on how this relationship changes over time'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='power_dynamic',
            field=models.CharField(choices=[('balanced', 'Balanced (=)'), ('a_dominant', 'Character A Dominant (>)'), ('b_dominant', 'Character B Dominant (<)')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='trust_level',
            field=models.PositiveIntegerField(default=5, help_text='Trust level (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
