# Generated by Django 4.2.27 on 2026-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0020_characterrelationship_evolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrelationship',
            name='character_a_wants',
            field=models.TextField(blank=True, help_text='What Character A wants from B'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='character_b_wants',
            field=models.TextField(blank=True, help_text='What Character B wants from A'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='conflict_source',
            field=models.TextField(blank=True, help_text='Source of conflict/tension'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('active', 'Active'), ('estranged', 'Estranged'), ('deceased', 'Deceased'), ('unresolved', 'Unresolved')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public Knowledge'), ('secret', 'Secret'), ('rumored', 'Rumored/Suspected')], default='public', max_length=20),
        ),
    ]
