# Generated by Django 4.2.27 on 2026-02-12 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0021_characterrelationship_character_a_wants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterrelationship',
            name='first_impression',
            field=models.TextField(blank=True, help_text='Their initial perception of each other'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='major_shared_moments',
            field=models.TextField(blank=True, help_text='Pivotal events that defined their bond'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='predictability',
            field=models.PositiveIntegerField(default=5, help_text='How well they anticipate each other (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='shared_secret',
            field=models.TextField(blank=True, help_text='Something only these two characters know'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='vulnerability',
            field=models.TextField(blank=True, help_text='What they hide from the other / their mutual weakness'),
        ),
    ]
