# Generated by Django 4.2.27 on 2026-02-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0022_characterrelationship_first_impression_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RelationshipAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_json', models.JSONField(help_text='The final suggested relationship metadata')),
                ('char_a_metadata_hash', models.CharField(help_text='Hash of traits/motivation for A', max_length=64)),
                ('char_b_metadata_hash', models.CharField(help_text='Hash of traits/motivation for B', max_length=64)),
                ('interaction_snapshots_hash', models.CharField(help_text='Hash of the 3 interaction summaries', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_caches', to='timeline.book')),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_a_caches', to='timeline.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_b_caches', to='timeline.character')),
            ],
            options={
                'unique_together': {('book', 'character_a', 'character_b')},
            },
        ),
        migrations.CreateModel(
            name='InteractionSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_index', models.PositiveIntegerField(help_text='0, 1, or 2 (for the 3 passes)')),
                ('summary_text', models.TextField()),
                ('content_hash', models.CharField(help_text='Hash of scene content/order to detect changes', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_caches', to='timeline.book')),
                ('character_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_a_caches', to='timeline.character')),
                ('character_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_b_caches', to='timeline.character')),
            ],
            options={
                'unique_together': {('book', 'character_a', 'character_b', 'batch_index')},
            },
        ),
    ]
