# Generated by Django 4.2.27 on 2026-02-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0023_alter_characterrelationship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('friend', 'Friend'), ('ally', 'Ally'), ('enemy', 'Enemy'), ('romantic', 'Romantic'), ('family', 'Family'), ('rival', 'Rival'), ('mentor', 'Mentor'), ('professional', 'Professional'), ('neutral', 'Neutral')], max_length=100),
        ),
    ]
