# Generated by Django 4.2.27 on 2026-02-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_alter_characterrelationship_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshipanalysiscache',
            name='interaction_snapshots_hash',
            field=models.CharField(help_text='Hash of the 3 interaction summaries', max_length=300),
        ),
    ]
