# Generated by Django 4.2.27 on 2026-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0025_alter_relationshipanalysiscache_interaction_snapshots_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_deep_scan',
            field=models.DateTimeField(blank=True, help_text='Last full AI analysis date', null=True),
        ),
        migrations.CreateModel(
            name='StoryScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, help_text="e.g. 'Analyzing Relationships (3/15)'", max_length=255)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_statuses', to='timeline.book')),
            ],
        ),
    ]
