# Generated by Django 4.2.27 on 2026-02-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0026_book_last_deep_scan_storyscanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyscanstatus',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_status', to='timeline.book'),
        ),
    ]
