# Generated by Django 4.2.27 on 2026-02-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0027_alter_storyscanstatus_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('friend', 'Friend'), ('ally', 'Ally'), ('enemy', 'Enemy'), ('romantic', 'Romantic'), ('family', 'Family'), ('rival', 'Rival'), ('mentor', 'Mentor'), ('protege', 'Protege / Apprentice'), ('professional', 'Professional'), ('acquaintance', 'Acquaintance'), ('complicated', 'Complicated / Ambiguous'), ('nemesis', 'Nemesis'), ('neutral', 'Neutral')], max_length=100),
        ),
    ]
