# Generated by Django 4.2.27 on 2026-02-23 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0029_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='e.g. v1.2.0', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('new', 'New Feature'), ('improvement', 'Improvement'), ('fix', 'Bug Fix'), ('ai', 'AI Update'), ('other', 'Other')], default='new', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
