# Generated by Django 4.2.27 on 2026-02-24 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0032_pennchat_pennmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['title'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.RemoveField(
            model_name='pennmessage',
            name='chat',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['series', 'series_order']},
        ),
        migrations.DeleteModel(
            name='PennChat',
        ),
        migrations.DeleteModel(
            name='PennMessage',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Which series does this book belong to?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='timeline.series'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user', 'series', 'series_order')},
        ),
    ]
