# Generated by Django 4.2.27 on 2026-02-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0033_series_remove_pennmessage_chat_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='core_desire',
            field=models.TextField(blank=True, help_text='What the character wants most'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='fatal_flaw',
            field=models.TextField(blank=True, help_text='The weakness that potentially leads to their downfall'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, help_text='e.g. 5\'10"', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('importing', 'Import in Progress'), ('planning', 'Planning'), ('drafting', 'Drafting'), ('editing', 'Editing'), ('complete', 'Complete'), ('published', 'Published'), ('archived', 'Archived')], default='planning', max_length=100),
        ),
    ]
