# Generated by Django 4.2.27 on 2026-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0034_character_age_character_core_desire_character_eyes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fears',
            field=models.TextField(blank=True, help_text='Their deepest phobias or anxieties'),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True, help_text='Character defects or moral shortcomings'),
        ),
        migrations.AddField(
            model_name='character',
            name='internal_conflicts',
            field=models.TextField(blank=True, help_text='The emotional tug-of-war they experience'),
        ),
        migrations.AddField(
            model_name='character',
            name='regrets',
            field=models.TextField(blank=True, help_text='Past actions or mistakes they feel deep remorse over'),
        ),
        migrations.AddField(
            model_name='character',
            name='secrets',
            field=models.TextField(blank=True, help_text='Information they are fiercely hiding'),
        ),
        migrations.AddField(
            model_name='character',
            name='unfulfilled_desires',
            field=models.TextField(blank=True, help_text='What they secretly yearn for but cannot achieve'),
        ),
    ]
