# Generated by Django 4.2.27 on 2026-02-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0035_character_fears_character_flaws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_assisted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='characters_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='ending_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
