# Generated by Django 4.2.27 on 2026-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0036_book_ai_assisted_book_characters_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inciting_incident',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='protagonist_motivation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='story_hook',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='world_atmosphere',
            field=models.TextField(blank=True, default=''),
        ),
    ]
