# Generated by Django 4.2.27 on 2026-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0037_book_inciting_incident_book_protagonist_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='consent_store_ip',
            field=models.BooleanField(default=False, help_text='User consent to store their IP address for security and analytics purposes'),
        ),
    ]
