# Generated by Django 4.2.27 on 2026-02-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0039_userprofile_technicalsupportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('writer_type', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('writing_groups', models.CharField(blank=True, max_length=200)),
                ('platform_preference', models.CharField(blank=True, max_length=200)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist Signup',
                'verbose_name_plural': 'Waitlist Signups',
                'ordering': ['-signed_up_at'],
            },
        ),
    ]
